### PR TITLE
ffmpeg input 

### PR DESCRIPTION
**Pull request by MaPePeR**
I'm experimenting with using ffmpeg directly instead of using vlc as a layer inbetween.

It compiles, runs and decodes and encodes "something". 

Have not listened to the result, yet, though.
Need to add an additional option that allows to specify the input format, so one can also use it for capturing alsa, etc.

Maybe you want to take a look at it.

### CODE REVIEW

**Comment by mpbraendli** [comment]
Thanks for the contribution!

Some feedback:
- README is missing a scenario and an explanation about tradeoffs between VLC and FFMPEG (Try to be impartial, I know you're biased on this question :-D )
- configure.ac line 57 has wrong description
- FFMPEGInput.h has no license header
- class FFMPEGInput is not documented (doxygen format)
- FFMPEGInput does not respect the C++ rule of three
- FFMPEGInput.cpp is missing your copyright. The licence header should be at the top of the file, the comment telling from where the code is taken can follow the header.
- I didn't check the code for memory leaks, did you try running the code through valgrind?
- I'll let you take care of the TODO and "Somehow this does not work" comments :-)
- Does it work with mono sources?
- Cosmetics: put `else` on a new line, not after `}`
- Prefer `reinterpret_cast<uint8_t*>()` over C-style cast `(uint8_t*)`
- Prefer `BYTES_PER_SAMPLE` macro over using `2`
- `goto end` is not so nice, prefer a function.

Let me know what you think!

**Comment by mpbraendli** [comment]
- configure.ac needs to check for availability of ffmpeg
- add a ffmpeg build to travis-ci

**Comment by MaPePeR** [comment]
- [ ] README is missing a scenario and an explanation about tradeoffs between VLC and FFMPEG (Try to be impartial, I know you're biased on this question :-D )
- [X] configure.ac line 57 has wrong description
- [ ] FFMPEGInput.h has no license header
- [ ] class FFMPEGInput is not documented (doxygen format)
- [ ] FFMPEGInput does not respect the C++ rule of three
- [X] FFMPEGInput.cpp is missing your copyright. The licence header should be at the top of the file, the comment telling from where the code is taken can follow the header.
- [ ] I didn't check the code for memory leaks, did you try running the code through valgrind?
- [X] I'll let you take care of the TODO and "Somehow this does not work" comments :-)
- [ ] Does it work with mono sources?
- [X] Cosmetics: put else on a new line, not after }
- [X] Prefer reinterpret_cast<uint8_t*>() over C-style cast (uint8_t*)
- [X] Prefer BYTES_PER_SAMPLE macro over using 2
- [ ] goto end is not so nice, prefer a function.
  - The `goto` is needed, because i need it to break out of a nested loop
- [X] configure.ac needs to check for availability of ffmpeg
- [x] add a ffmpeg build to travis-ci

**Comment by mpbraendli** [comment]
> goto end is not so nice, prefer a function.
>> The goto is needed, because i need it to break out of a nested loop

"breaking out of a nested loop" is exactly why I'm suggesting a function :-) You can call `return` from the inside loop.

**Pull request closed without merging**
